### ISSUE TITLE
As a player I want to see who wins in order to congratulate him in the chat

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#14]
Acceptance Criteria:
- [x] If all rounds were played, no new round is initiated and a leaderboard is shown, crowning the player with the most points
- [x] An winning animation could be shown to crown the best player

Development Tasks:
- [x] sopra-fs22-group28/sopra-fs22-group28-server#94
- [x] sopra-fs22-group28/sopra-fs22-group28-client#64
- [x] #149
- [x] #150

**Comment by tnaescher** [comment]
Completed
