### ISSUE TITLE
As a player I want to be able to see immediately after the round ends if my answers are unique or if another Player has the same answers in order to have an immediate feedback on the solutions

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#15]
Acceptance Criteria:
- [x] Unique answers can be highlighted in a different color so one can see very fast which answers were unique from the other.
- [x] Unique answers give double the points than answers multiple players have the same

Development Tasks:
- [x] #142
- [x] #143
- [x] #146

**Comment by tnaescher** [comment]
Completed
