### ISSUE TITLE
As a programmer of our game I want to have all the required tests in the server for M3 in order to be safe with the code created and the future code

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#85]
Acceptance Criteria
- [x] The test coverage should be for the deadline M3 at least 50%
- [x] The test should be written in a good way and have good descriptions in the title so that one knows what is tested

Development tasks
- [x] #86
- [x] #87
- [x] #88

**Comment by tnaescher** [comment]
Completed
